#!/bin/bash
cd /home/ubuntu && git clone https://github.com/iam-amitkumar/ChatApp.git
sudo mkdir /home/ubuntu/amitkr.txt
"Hello World" > amitkr.txt
sudo echo "<h1>Hello Amit</h1>" > /var/www/html/index.html
